#mv media/P10.png media/Gr10.png
#mv media/P1.png media/Gr1.png
#mv media/P2.png media/Gr2.png
#mv media/P3.png media/Gr3.png
#mv media/P4.png media/Gr4.png
#mv media/P5.png media/Gr5.png
#mv media/P6.png media/Gr6.png
#mv media/P7.png media/Gr7.png
#mv media/P8.png media/Gr8.png
#mv media/P9.png media/Gr9.png
mv media/pe10.png media/GEs10.png
mv media/pe1.png media/GEs1.png
mv media/pe2.png media/GEs2.png
mv media/pe3.png media/GEs3.png
mv media/pe4.png media/GEs4.png
mv media/pe5.png media/GEs5.png
mv media/pe6.png media/GEs6.png
mv media/pe7.png media/GEs7.png
mv media/pe8.png media/GEs8.png
mv media/pe9.png media/GEs9.png
